CONFIG_GPIO=y
CONFIG_INPUT=y

# Filesystem stuff
CONFIG_DISK_ACCESS=y
CONFIG_DISK_DRIVER_SDMMC=y
CONFIG_LOG=y
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_PRINTK=y
CONFIG_MAIN_STACK_SIZE=2048
# Important for longer names and filesystem navigation to work properly
CONFIG_FS_FATFS_LFN=y
CONFIG_INPUT_THREAD_STACK_SIZE=4098

# Bluetooth Stack (Single SoC, Host and Controller configuration)
# CONFIG_BT=y
# CONFIG_BT_HCI=y
# Board will act as a GAP Central, scanning for the earbud and initiate the
# connection. 
# CONFIG_BT_CENTRAL=y
# Allows pairing (remember connections)
# CONFIG_BT_SMP=y

# LE Audio
# CONFIG_BT_AUDIO=y

CONFIG_DEBUG=y
# CONFIG_SD_LOG_LEVEL_DBG=y
# CONFIG_SDHC_LOG_LEVEL_DBG=y
# CONFIG_SDMMC_LOG_LEVEL_DBG=y